apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-declarativo
  namespace: aula1
spec:
  containers:
    - name: nginx-container
      image: nginx:stable
      ports:
        - containerPort: 80
      imagePullPolicy: Always
    - name: primeiro-app
      image: hugaleno/kub-firstapp