apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-hooks
  namespace: aula1
spec:
  containers:
    - name: nginx-container
      image: nginx:stable
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "mkdir /diretorioinexistente/teste"]
        preStop:
          exec:
            command: ["/bin/sh", "-c", "echo PreStop Handler >> /usr/share/message;sleep 60"]
        