apiVersion: v1
kind: Pod
metadata:
  name: pod-live
  namespace: aula1
spec:
  containers:
    - name: live-container
      image: k8s.gcr.io/liveness
      args:
        - /server
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
          httpHeaders:
            - name: Header-Qualquer
              value: Valor
        initialDelaySeconds: 5
        periodSeconds: 5
