apiVersion: v1
kind: Pod
metadata:
  name: pod-limit
  namespace: aula1
spec:
  containers:
    - name: limit-container
      image: polinux/stress
      resources:
        limits:
          memory: "10000Gi"
        requests:
          memory: "5000Gi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]